# Generated by Django 4.0.6 on 2022-07-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_organizer_meetup_date_meetup_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='Organizer',
        ),
        migrations.AddField(
            model_name='meetup',
            name='Organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetups.organizer'),
            preserve_default=False,
        ),
    ]
