# Generated by Django 4.0.6 on 2022-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_remove_meetup_organizer_meetup_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='Organizer',
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='test@test.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
