# Generated by Django 4.0.6 on 2022-07-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_remove_meetup_organizer_meetup_organizer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('OrgEmail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='organizer_email',
        ),
        migrations.AddField(
            model_name='meetup',
            name='Organizer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='meetups.organizer'),
            preserve_default=False,
        ),
    ]
